package ua.lviv.iot;
public enum DeviceType {
    HOOVER, REFRIGERATOR, TV, IRON, HAIRDRIER, WASHINGMACHINE, ELECTRICSTOVE, AIRCONDITINING, DISHWASHER,
    ELECTRICKETTLE, MICROWAVE, MULTITOOL, OTHER
}
